CREATE TABLE AVIONES_A (
  AVION_ID      NUMBER PRIMARY KEY,
  MODELO        VARCHAR2(100) NOT NULL,
  FABRICANTE    VARCHAR2(100),
  ANO_INGRESO   NUMBER(4),
  TIPO          VARCHAR2(50),
  OBSERVACIONES VARCHAR2(4000)
);

CREATE TABLE CASCOS (
  CASCO_ID     NUMBER PRIMARY KEY,
  AVION_ID     NUMBER NOT NULL,
  TALLA        VARCHAR2(10),
  MARCA        VARCHAR2(100),
  MODELO       VARCHAR2(100),
  ESTADO       VARCHAR2(50),
  FECHA_ENTREGA DATE,
  CONSTRAINT FK_CASCOS_AVIONES FOREIGN KEY (AVION_ID) REFERENCES AVIONES_A(AVION_ID)
);

CREATE SEQUENCE AVIONES_A_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CASCOS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IDX_AVIONES_MODELO ON AVIONES_A(MODELO);
CREATE INDEX IDX_CASCOS_ESTADO ON CASCOS(ESTADO);

COMMIT;