CREATE OR REPLACE PROCEDURE POPULATE_SAMPLE_DATA IS
BEGIN
  DELETE FROM CASCOS;
  DELETE FROM AVIONES_A;
  COMMIT;

  -- Inserta 15 aviones
  INSERT INTO AVIONES_A(AVION_ID, MODELO, FABRICANTE, ANO_INGRESO, TIPO, OBSERVACIONES)
  VALUES(AVIONES_A_SEQ.NEXTVAL,'F-16A Fighting Falcon','General Dynamics',1990,'Caza','Grupo A');
  -- ... (resto de inserts del documento original)

  COMMIT;

  FOR r IN (SELECT AVION_ID, MODELO FROM AVIONES_A) LOOP
    INSERT INTO CASCOS(CASCO_ID, AVION_ID, TALLA, MARCA, MODELO, ESTADO, FECHA_ENTREGA)
    VALUES (CASCOS_SEQ.NEXTVAL, r.AVION_ID,
            CASE WHEN MOD(r.AVION_ID,3)=0 THEN 'L' WHEN MOD(r.AVION_ID,3)=1 THEN 'M' ELSE 'S' END,
            'HelmoCorp', r.MODELO || ' - H1', 'Bueno', SYSDATE - MOD(r.AVION_ID,30));
  END LOOP;

  COMMIT;
END POPULATE_SAMPLE_DATA;
/

COMMIT;